name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: cargo install --git https://github.com/jgouly/cube-tools --bin alg-list-gen
    - name: Run tests
      run: alg-list-gen < edges.html
